import {
  type CSSProperties,
  useCallback,
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { createPortal } from "react-dom";
import { invoke, isTauri } from "@tauri-apps/api/core";
import { GamepadCollectionSettingsPromptGlyph } from "./GamepadCollectionSettingsPromptGlyph";
import { GamepadHorizontalNavPromptGlyphs } from "./GamepadHorizontalNavPromptGlyphs";
import { GamepadPromptGlyph } from "./GamepadPromptGlyph";
import {
  GamepadSelectPromptGlyph,
  GamepadStartPromptGlyph,
} from "./GamepadStartSelectPromptGlyphs";
import {
  KeyboardBackGlyph,
  KeyboardCollectionSettingsGlyph,
  KeyboardMoveHorizontalGlyph,
  KeyboardRefreshGlyph,
  KeyboardSettingsGlyph,
} from "./KeyboardCollectionsHintGlyphs";
import { KeyboardEnterPromptGlyph } from "./KeyboardNavPromptGlyphs";
import { useCollectionsGamepadNavigation } from "./useCollectionsGamepadNavigation";
import { useGamepadInput } from "./useGamepadFlavor";
import { fetchCollectionBackgroundUrl } from "./collectionBackground";
import { fetchCollectionGridCoverUrl } from "./collectionGridCover";
import { fetchSteamGridSearchQuery } from "./collectionSteamGridSearch";
import { collectionRowKey } from "./collectionKey";
import {
  getCollectionPrefs,
  isCollectionHidden,
  patchCollectionPrefs,
  unhideAllCollections,
} from "./collectionLauncherPrefs";
import { getGamePrefs, patchGamePrefs } from "./gameLauncherPrefs";
import {
  FETCH_CONCURRENCY,
  fetchReleaseYearLabel,
  mapPool,
} from "./collectionReleaseYears";
import {
  fetchGameSteamGridBackgroundUrl,
  fetchGameSteamGridCoverUrl,
  getCachedGameSteamGridBackgroundUrl,
} from "./gameSteamGridArt";
import { rommAssetUrl } from "./rommAssets";
import { fetchGamesForCollection, type RommGame } from "./rommGames";
import {
  getSteamGridDbApiKey,
  loadSteamGridDbApiKey,
  saveSteamGridDbApiKey,
} from "./steamGridDbSettings";
import {
  loadVirtualCollectionType,
  saveVirtualCollectionType,
  type VirtualCollectionType,
} from "./virtualCollectionType";
import "./CollectionsView.css";

export type Session = {
  apiBase: string;
  accessToken: string;
};

export type RommCollection = {
  /** Numeric for manual/smart collections; base64 string for virtual (autogenerated). */
  id: number | string;
  name: string;
  description?: string;
  rom_count?: number;
  path_cover_small?: string | null;
  path_cover_large?: string | null;
  /** Virtual / autogenerated collections use mosaic paths (RomM API). */
  path_covers_small?: string[] | null;
  path_covers_large?: string[] | null;
  url_cover?: string | null;
  created_at?: string;
  updated_at?: string;
  is_smart?: boolean;
  is_virtual?: boolean;
  /** RomM virtual collection category (e.g. franchise grouping). */
  collection_type?: string;
  /** Member ROM ids (RomM includes this on collection payloads). */
  rom_ids?: number[];
};

type Props = {
  session: Session;
  onLogout: () => void;
};

type CarouselDisplayItem = {
  key: string;
  title: string;
  meta: string;
  coverUrl?: string;
  backgroundUrl?: string;
  showTimeline: boolean;
};

type BackgroundLayer = {
  id: number;
  url?: string;
  active: boolean;
};

function formatInvokeError(err: unknown): string {
  if (typeof err === "string") return err;
  if (err instanceof Error) return err.message;
  try {
    return JSON.stringify(err);
  } catch {
    return String(err);
  }
}

function firstCoverUrl(
  apiBase: string,
  paths: string[] | null | undefined,
): string | undefined {
  if (!paths?.length) return undefined;
  return rommAssetUrl(apiBase, paths[0]);
}

function coverForCollection(apiBase: string, c: RommCollection): string | undefined {
  return (
    rommAssetUrl(apiBase, c.path_cover_large) ??
    rommAssetUrl(apiBase, c.path_cover_small) ??
    firstCoverUrl(apiBase, c.path_covers_large) ??
    firstCoverUrl(apiBase, c.path_covers_small) ??
    rommAssetUrl(apiBase, c.url_cover ?? undefined)
  );
}

function coverForCarouselSlot(
  apiBase: string,
  c: RommCollection,
  gridCovers: Record<string, string | undefined>,
): string | undefined {
  const k = collectionRowKey(c);
  const idx = getCollectionPrefs(k).coverSteamIndex ?? -1;
  if (idx >= 0) {
    const g = gridCovers[k];
    if (g) return g;
  }
  return coverForCollection(apiBase, c);
}

function coverForGameCarouselSlot(
  game: RommGame,
  gridCovers: Record<string, string | undefined>,
): string | undefined {
  const idx = getGamePrefs(game.key, game.name).coverSteamIndex ?? -1;
  if (idx >= 0) {
    const g = gridCovers[game.key];
    if (g) return g;
  }
  return game.coverUrl;
}

/** First line under poster: min–max game release years from RomM `/roms` metadata. */
function metaPrimaryLine(
  resolved: string | undefined,
  spansLoading: boolean,
): string {
  if (resolved !== undefined) return resolved;
  if (spansLoading) return "…";
  return "—";
}

/** Match `.collection-slot` width: `clamp(100px, 14vw, 160px)` (vw = window). */
function estimateCollectionSlotWidthPx(): number {
  if (typeof window === "undefined") return 130;
  return Math.min(160, Math.max(100, window.innerWidth * 0.14));
}

/** Match `.collections-carousel-track` gap: `clamp(12px, 2.5vw, 28px)`. */
function estimateCollectionGapPx(): number {
  if (typeof window === "undefined") return 20;
  return Math.min(28, Math.max(12, window.innerWidth * 0.025));
}

const MAX_CAROUSEL_SLOT_RADIUS = 30;
const BACKGROUND_CROSSFADE_MS = 320;

/** Settings panel: IGDB, franchise, SteamGrid key, save, unhide. */
const SETTINGS_NAV_SLOTS = 5;

/** Per-collection panel: hide, next hero, next cover. */
/** Hide + SteamGrid hero (prev/next/clear) + cover (prev/next/clear). */
const COLLECTION_SETTINGS_NAV_SLOTS = 7;
const GAME_SETTINGS_NAV_SLOTS = 6;

/**
 * Signed minimal index delta on the ring → slide direction.
 * (The old “forward modular distance ≤ n/2” rule breaks for n=2: both steps are length 1
 * but left must be “prev”, not “next”.)
 */
function focusNavSlideDir(from: number, to: number, len: number): "next" | "prev" {
  if (len <= 1) return "next";
  let d = to - from;
  if (d > len / 2) d -= len;
  if (d < -len / 2) d += len;
  return d > 0 ? "next" : "prev";
}

type CarouselTransition = { dir: "next" | "prev"; from: number; to: number };

function carouselSlotContentAnimClass(
  t: CarouselTransition | null,
  p: {
    idx: number;
    offset: number;
    isFocus: boolean;
    isPlaceholder: boolean;
    slotRadius: number;
  },
): string {
  if (!t || p.isPlaceholder) return "";
  if (p.isFocus) {
    return t.dir === "next"
      ? " collection-slot-content--slide-next"
      : " collection-slot-content--slide-prev";
  }
  if (p.idx === t.from) {
    return t.dir === "next"
      ? " collection-slot-content--leave-next"
      : " collection-slot-content--leave-prev";
  }
  const r = p.slotRadius;
  if (r > 0) {
    if (t.dir === "next" && p.offset === r) {
      return " collection-slot-content--enter-next";
    }
    if (t.dir === "prev" && p.offset === -r) {
      return " collection-slot-content--enter-prev";
    }
  }
  return "";
}

function backgroundImageStyle(url: string | undefined): CSSProperties | undefined {
  if (!url) return undefined;
  return {
    backgroundImage: `url("${url.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}")`,
  };
}

/** Track width: one centered slot is scaled (~1.05); matches `.collection-slot--focus`. */
function carouselTrackWidthPx(n: number, slotW: number, gap: number): number {
  if (n < 1) return 0;
  return (n - 1) * slotW + slotW * 1.05 + (n - 1) * gap;
}

/**
 * Half-width of the offset window [−r … +r] so an odd number of slots fits in `width`.
 */
function computeCarouselSlotRadius(width: number): number {
  if (!Number.isFinite(width) || width < 60) return 0;
  const slotW = estimateCollectionSlotWidthPx();
  const gap = estimateCollectionGapPx();
  const safety = 1.035;
  const budget = width * 0.998;
  let n = 1;
  const maxSlots = MAX_CAROUSEL_SLOT_RADIUS * 2 + 1;
  while (n + 2 <= maxSlots) {
    const next = n + 2;
    const raw = carouselTrackWidthPx(next, slotW, gap);
    if (raw * safety > budget) break;
    n = next;
  }
  return (n - 1) / 2;
}

async function fetchCollectionArrays(
  session: Session,
  virtualType: VirtualCollectionType,
): Promise<RommCollection[]> {
  const regularP = invoke<string>("romm_api_get", {
    apiBase: session.apiBase,
    accessToken: session.accessToken,
    path: "collections",
    query: null,
  });
  const smartP = invoke<string>("romm_api_get", {
    apiBase: session.apiBase,
    accessToken: session.accessToken,
    path: "collections/smart",
    query: null,
  });
  /** Autogenerated virtual groups — one IGDB bucket (`franchise` or `collection`). */
  const virtualP = invoke<string>("romm_api_get", {
    apiBase: session.apiBase,
    accessToken: session.accessToken,
    path: "collections/virtual",
    query: `type=${virtualType}`,
  });

  const [regOutcome, smartOutcome, virtOutcome] = await Promise.allSettled([
    regularP,
    smartP,
    virtualP,
  ]);

  const taggedRegular: RommCollection[] = [];
  if (regOutcome.status === "fulfilled") {
    try {
      const regular = JSON.parse(regOutcome.value) as RommCollection[];
      if (Array.isArray(regular)) {
        taggedRegular.push(...regular.map((c) => ({ ...c, is_smart: false })));
      }
    } catch {
      /* ignore malformed */
    }
  }

  const taggedSmart: RommCollection[] = [];
  if (smartOutcome.status === "fulfilled") {
    try {
      const smart = JSON.parse(smartOutcome.value) as RommCollection[];
      if (Array.isArray(smart)) {
        taggedSmart.push(...smart.map((c) => ({ ...c, is_smart: true })));
      }
    } catch {
      /* ignore malformed */
    }
  }

  const taggedVirtual: RommCollection[] = [];
  if (virtOutcome.status === "fulfilled") {
    try {
      const virtual = JSON.parse(virtOutcome.value) as Record<
        string,
        unknown
      >[];
      if (Array.isArray(virtual)) {
        for (const row of virtual) {
          const typeField =
            typeof row.type === "string" ? row.type : undefined;
          taggedVirtual.push({
            ...(row as unknown as RommCollection),
            is_smart: false,
            is_virtual: true,
            collection_type: typeField,
          });
        }
      }
    } catch {
      /* ignore malformed */
    }
  }

  const combined = [
    ...taggedRegular,
    ...taggedSmart,
    ...taggedVirtual,
  ].sort((a, b) =>
    a.name.localeCompare(b.name, undefined, { sensitivity: "base" }),
  );

  if (combined.length === 0) {
    if (regOutcome.status === "rejected") throw regOutcome.reason;
    if (virtOutcome.status === "rejected") throw virtOutcome.reason;
    if (smartOutcome.status === "rejected") throw smartOutcome.reason;
  }

  return combined;
}

export function CollectionsView({ session, onLogout }: Props) {
  const { flavor: gamepadFlavor, gamepadConnected } = useGamepadInput();
  const tauriShell = isTauri();
  const showGamepadHints = tauriShell && gamepadConnected;

  const [virtualType, setVirtualType] = useState<VirtualCollectionType>(() =>
    loadVirtualCollectionType(),
  );
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [collectionSettingsOpen, setCollectionSettingsOpen] = useState(false);
  const [collectionSettingsTarget, setCollectionSettingsTarget] =
    useState<RommCollection | null>(null);
  const [collectionSettingsNavIndex, setCollectionSettingsNavIndex] =
    useState(0);
  const [gameSettingsOpen, setGameSettingsOpen] = useState(false);
  const [gameSettingsTarget, setGameSettingsTarget] =
    useState<RommGame | null>(null);
  const [gameSettingsNavIndex, setGameSettingsNavIndex] = useState(0);
  const [prefsRev, setPrefsRev] = useState(0);
  const [gridCovers, setGridCovers] = useState<
    Record<string, string | undefined>
  >({});
  const [gameGridCovers, setGameGridCovers] = useState<
    Record<string, string | undefined>
  >({});
  const [items, setItems] = useState<RommCollection[]>([]);
  const [activeCollection, setActiveCollection] = useState<RommCollection | null>(
    null,
  );
  const [games, setGames] = useState<RommGame[]>([]);
  const [focusIndex, setFocusIndex] = useState(0);
  const [gamesFocusIndex, setGamesFocusIndex] = useState(0);
  const [loading, setLoading] = useState(true);
  const [gamesLoading, setGamesLoading] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [gamesError, setGamesError] = useState<string | null>(null);
  const [releaseLabels, setReleaseLabels] = useState<Record<string, string>>(
    {},
  );
  const [yearSpansLoading, setYearSpansLoading] = useState(false);
  const carouselViewportRef = useRef<HTMLDivElement>(null);
  const carouselTrackRef = useRef<HTMLDivElement>(null);
  const focusSlotRef = useRef<HTMLButtonElement | null>(null);
  const focusIndexRef = useRef(0);
  const prevFocusForSlideRef = useRef<number | null>(null);
  const [carouselTransition, setCarouselTransition] =
    useState<CarouselTransition | null>(null);
  const settingsWrapRef = useRef<HTMLDivElement>(null);
  const settingsRadioCollectionRef = useRef<HTMLInputElement>(null);
  const settingsRadioFranchiseRef = useRef<HTMLInputElement>(null);
  const settingsSteamKeyRef = useRef<HTMLInputElement>(null);
  const settingsSaveRef = useRef<HTMLButtonElement>(null);
  const settingsUnhideAllRef = useRef<HTMLButtonElement>(null);
  const collectionHideRef = useRef<HTMLButtonElement>(null);
  const collectionPrevHeroRef = useRef<HTMLButtonElement>(null);
  const collectionNextHeroRef = useRef<HTMLButtonElement>(null);
  const collectionClearHeroRef = useRef<HTMLButtonElement>(null);
  const collectionPrevCoverRef = useRef<HTMLButtonElement>(null);
  const collectionNextCoverRef = useRef<HTMLButtonElement>(null);
  const collectionClearCoverRef = useRef<HTMLButtonElement>(null);
  const gamePrevHeroRef = useRef<HTMLButtonElement>(null);
  const gameNextHeroRef = useRef<HTMLButtonElement>(null);
  const gameClearHeroRef = useRef<HTMLButtonElement>(null);
  const gamePrevCoverRef = useRef<HTMLButtonElement>(null);
  const gameNextCoverRef = useRef<HTMLButtonElement>(null);
  const gameClearCoverRef = useRef<HTMLButtonElement>(null);
  const [settingsNavIndex, setSettingsNavIndex] = useState(0);
  const [slotRadius, setSlotRadius] = useState(2);
  const [steamGridKeyDraft, setSteamGridKeyDraft] = useState(() =>
    loadSteamGridDbApiKey(),
  );
  const [steamSettingsRev, setSteamSettingsRev] = useState(0);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      setLoading(true);
      setError(null);
      try {
        const list = await fetchCollectionArrays(session, virtualType);
        if (!cancelled) {
          setItems(list);
          setFocusIndex(0);
        }
      } catch (e) {
        if (!cancelled) setError(formatInvokeError(e));
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [session, virtualType]);

  const inGamesView = activeCollection !== null;

  useEffect(() => {
    if (!activeCollection) {
      setGames([]);
      setGamesFocusIndex(0);
      setGamesLoading(false);
      setGamesError(null);
      return;
    }

    let cancelled = false;
    setGames([]);
    setGamesFocusIndex(0);
    setGamesLoading(true);
    setGamesError(null);

    void (async () => {
      try {
        const list = await fetchGamesForCollection(session, activeCollection);
        if (!cancelled) {
          setGames(list);
          setGamesFocusIndex(0);
        }
      } catch (e) {
        if (!cancelled) setGamesError(formatInvokeError(e));
      } finally {
        if (!cancelled) setGamesLoading(false);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [activeCollection, session]);

  const visibleItems = useMemo(
    () => items.filter((c) => !isCollectionHidden(c)),
    [items, prefsRev],
  );

  useEffect(() => {
    if (visibleItems.length === 0) {
      setFocusIndex(0);
      return;
    }
    setFocusIndex((i) => Math.min(i, visibleItems.length - 1));
  }, [visibleItems.length]);

  useEffect(() => {
    if (games.length === 0) {
      setGamesFocusIndex(0);
      return;
    }
    setGamesFocusIndex((i) => Math.min(i, games.length - 1));
  }, [games.length]);

  const collectionCards = useMemo<CarouselDisplayItem[]>(
    () =>
      visibleItems.map((c) => ({
        key: collectionRowKey(c),
        title: c.name,
        meta: metaPrimaryLine(
          releaseLabels[collectionRowKey(c)],
          yearSpansLoading,
        ),
        coverUrl: coverForCarouselSlot(session.apiBase, c, gridCovers),
        showTimeline: false,
      })),
    [
      visibleItems,
      releaseLabels,
      yearSpansLoading,
      session.apiBase,
      gridCovers,
      prefsRev,
    ],
  );

  const gameCards = useMemo<CarouselDisplayItem[]>(
    () =>
      games.map((game) => ({
        key: game.key,
        title: game.name,
        meta: game.yearLabel,
        coverUrl: coverForGameCarouselSlot(game, gameGridCovers),
        backgroundUrl: game.backgroundUrl,
        showTimeline: true,
      })),
    [games, gameGridCovers, prefsRev],
  );

  const currentCards = inGamesView ? gameCards : collectionCards;
  const currentFocusIndex = inGamesView ? gamesFocusIndex : focusIndex;
  const currentLoading = inGamesView ? gamesLoading : loading;
  const currentError = inGamesView ? gamesError : error;

  useEffect(() => {
    focusIndexRef.current = currentFocusIndex;
  }, [currentFocusIndex]);

  useLayoutEffect(() => {
    if (currentCards.length <= 1) {
      prevFocusForSlideRef.current = currentFocusIndex;
      return;
    }
    const prev = prevFocusForSlideRef.current;
    if (prev === null) {
      prevFocusForSlideRef.current = currentFocusIndex;
      return;
    }
    if (prev === currentFocusIndex) return;
    if (
      typeof window !== "undefined" &&
      window.matchMedia("(prefers-reduced-motion: reduce)").matches
    ) {
      prevFocusForSlideRef.current = currentFocusIndex;
      return;
    }
    setCarouselTransition({
      dir: focusNavSlideDir(prev, currentFocusIndex, currentCards.length),
      from: prev,
      to: currentFocusIndex,
    });
    prevFocusForSlideRef.current = currentFocusIndex;
  }, [currentCards.length, currentFocusIndex]);

  useEffect(() => {
    if (!carouselTransition) return;
    const timer = window.setTimeout(() => setCarouselTransition(null), 420);
    return () => window.clearTimeout(timer);
  }, [carouselTransition]);

  useEffect(() => {
    prevFocusForSlideRef.current = null;
    setCarouselTransition(null);
  }, [activeCollection]);

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      const sgKey = getSteamGridDbApiKey()?.trim();
      if (!isTauri() || !sgKey) {
        if (!cancelled) setGridCovers({});
        return;
      }
      const next: Record<string, string | undefined> = {};
      for (const c of items) {
        const k = collectionRowKey(c);
        const idx = getCollectionPrefs(k).coverSteamIndex ?? -1;
        if (idx >= 0) {
          const u = await fetchCollectionGridCoverUrl(session, c, idx);
          if (cancelled) return;
          if (u) next[k] = u;
        }
      }
      if (!cancelled) setGridCovers(next);
    })();
    return () => {
      cancelled = true;
    };
  }, [items, prefsRev]);

  useEffect(() => {
    if (!activeCollection || games.length === 0) {
      setGameGridCovers({});
      return;
    }

    let cancelled = false;
    void (async () => {
      const sgKey = getSteamGridDbApiKey()?.trim();
      if (!isTauri() || !sgKey) {
        if (!cancelled) setGameGridCovers({});
        return;
      }
      const next: Record<string, string | undefined> = {};
      for (const game of games) {
        const idx = getGamePrefs(game.key, game.name).coverSteamIndex ?? -1;
        if (idx >= 0) {
          const url = await fetchGameSteamGridCoverUrl(game, idx);
          if (cancelled) return;
          if (url) next[game.key] = url;
        }
      }
      if (!cancelled) setGameGridCovers(next);
    })();

    return () => {
      cancelled = true;
    };
  }, [activeCollection, games, prefsRev, steamSettingsRev]);

  useEffect(() => {
    if (loading || items.length === 0) {
      setReleaseLabels({});
      setYearSpansLoading(false);
      return;
    }
    let cancelled = false;
    setReleaseLabels({});
    setYearSpansLoading(true);
    void (async () => {
      await mapPool(items, FETCH_CONCURRENCY, async (c) => {
        const key = collectionRowKey(c);
        try {
          const label = await fetchReleaseYearLabel(session, c);
          if (!cancelled) {
            setReleaseLabels((prev) => ({ ...prev, [key]: label }));
          }
        } catch {
          if (!cancelled) {
            setReleaseLabels((prev) => ({ ...prev, [key]: "—" }));
          }
        }
      });
      if (!cancelled) setYearSpansLoading(false);
    })();
    return () => {
      cancelled = true;
      setYearSpansLoading(false);
    };
  }, [session, items, loading]);

  const onRefreshLibrary = useCallback(async () => {
    setRefreshing(true);
    if (activeCollection) {
      setGamesError(null);
      try {
        const list = await fetchGamesForCollection(session, activeCollection);
        setGames(list);
        setGamesFocusIndex((i) =>
          list.length === 0 ? 0 : Math.min(i, list.length - 1),
        );
      } catch (e) {
        setGamesError(formatInvokeError(e));
      } finally {
        setRefreshing(false);
      }
      return;
    }

    setError(null);
    try {
      const list = await fetchCollectionArrays(session, virtualType);
      setItems(list);
      setFocusIndex((i) =>
        list.length === 0 ? 0 : Math.min(i, list.length - 1),
      );
    } catch (e) {
      setError(formatInvokeError(e));
    } finally {
      setRefreshing(false);
    }
  }, [activeCollection, session, virtualType]);

  const toggleSettings = useCallback(() => {
    setCollectionSettingsOpen(false);
    setCollectionSettingsTarget(null);
    setGameSettingsOpen(false);
    setGameSettingsTarget(null);
    setSettingsOpen((prev) => {
      if (!prev) {
        setSteamGridKeyDraft(loadSteamGridDbApiKey());
        setSettingsNavIndex(virtualType === "franchise" ? 1 : 0);
      }
      return !prev;
    });
  }, [virtualType]);

  const closeCollectionSettings = useCallback(() => {
    setCollectionSettingsOpen(false);
    setCollectionSettingsTarget(null);
    setGameSettingsOpen(false);
    setGameSettingsTarget(null);
  }, []);

  const openGamesView = useCallback(() => {
    if (settingsOpen || collectionSettingsOpen || visibleItems.length === 0) return;
    const target = visibleItems[focusIndexRef.current];
    if (!target) return;
    closeCollectionSettings();
    setActiveCollection(target);
  }, [
    closeCollectionSettings,
    collectionSettingsOpen,
    settingsOpen,
    visibleItems,
  ]);

  const goBack = useCallback(() => {
    if (activeCollection) {
      setActiveCollection(null);
      return;
    }
    onLogout();
  }, [activeCollection, onLogout]);

  const toggleCollectionSettings = useCallback(() => {
    if (activeCollection) {
      if (gameSettingsOpen) {
        closeCollectionSettings();
        return;
      }
      if (settingsOpen || games.length === 0) return;
      const target = games[gamesFocusIndex];
      if (!target) return;
      setGameSettingsTarget(target);
      setGameSettingsNavIndex(0);
      setGameSettingsOpen(true);
      return;
    }
    if (collectionSettingsOpen) {
      closeCollectionSettings();
      return;
    }
    if (settingsOpen || visibleItems.length === 0) return;
    const t = visibleItems[focusIndex];
    if (!t) return;
    setCollectionSettingsTarget(t);
    setCollectionSettingsNavIndex(0);
    setCollectionSettingsOpen(true);
  }, [
    collectionSettingsOpen,
    closeCollectionSettings,
    settingsOpen,
    visibleItems,
    focusIndex,
    activeCollection,
    gameSettingsOpen,
    games,
    gamesFocusIndex,
  ]);

  const saveSteamGridKey = useCallback(() => {
    saveSteamGridDbApiKey(steamGridKeyDraft);
    setSteamSettingsRev((n) => n + 1);
  }, [steamGridKeyDraft]);

  const onUnhideAllCollections = useCallback(() => {
    unhideAllCollections();
    setPrefsRev((n) => n + 1);
  }, []);

  const activateSettingsNav = useCallback(() => {
    switch (settingsNavIndex) {
      case 0:
        settingsRadioCollectionRef.current?.click();
        break;
      case 1:
        settingsRadioFranchiseRef.current?.click();
        break;
      case 2:
        settingsSteamKeyRef.current?.focus();
        break;
      case 3:
        saveSteamGridKey();
        break;
      case 4:
        onUnhideAllCollections();
        break;
      default:
        break;
    }
  }, [settingsNavIndex, saveSteamGridKey, onUnhideAllCollections]);

  const prevHeroSteam = useCallback(async () => {
    const c = collectionSettingsTarget;
    if (!c || !isTauri()) return;
    const key = getSteamGridDbApiKey()?.trim();
    if (!key) return;
    const rowKey = collectionRowKey(c);
    const cur = getCollectionPrefs(rowKey).heroSteamIndex ?? -1;
    if (cur < 0) return;
    const next = cur - 1;
    if (next < 0) {
      patchCollectionPrefs(rowKey, { heroSteamIndex: -1 });
      setHeroBg(null);
      setPrefsRev((n) => n + 1);
      return;
    }
    const searchQuery = await fetchSteamGridSearchQuery(session, c);
    try {
      const url = await invoke<string | null>("steamgriddb_hero_url_at", {
        apiKey: key,
        searchQuery,
        index: next,
      });
      if (!url || url.length === 0) return;
      patchCollectionPrefs(rowKey, { heroSteamIndex: next });
      setHeroBg({ key: rowKey, url });
    } catch {
      return;
    }
    setPrefsRev((n) => n + 1);
  }, [collectionSettingsTarget, session]);

  const nextHeroSteam = useCallback(async () => {
    const c = collectionSettingsTarget;
    if (!c || !isTauri()) return;
    const key = getSteamGridDbApiKey()?.trim();
    if (!key) return;
    const rowKey = collectionRowKey(c);
    const searchQuery = await fetchSteamGridSearchQuery(session, c);
    const cur = getCollectionPrefs(rowKey).heroSteamIndex ?? -1;
    const next = cur + 1;
    try {
      const url = await invoke<string | null>("steamgriddb_hero_url_at", {
        apiKey: key,
        searchQuery,
        index: next,
      });
      if (!url || url.length === 0) return;
      patchCollectionPrefs(rowKey, { heroSteamIndex: next });
      setHeroBg({ key: rowKey, url });
    } catch {
      return;
    }
    setPrefsRev((n) => n + 1);
  }, [collectionSettingsTarget, session]);

  const clearHeroSteam = useCallback(() => {
    const c = collectionSettingsTarget;
    if (!c) return;
    patchCollectionPrefs(collectionRowKey(c), { heroSteamIndex: -1 });
    setHeroBg(null);
    setPrefsRev((n) => n + 1);
  }, [collectionSettingsTarget]);

  const prevCoverSteam = useCallback(async () => {
    const c = collectionSettingsTarget;
    if (!c || !isTauri()) return;
    const key = getSteamGridDbApiKey()?.trim();
    if (!key) return;
    const rowKey = collectionRowKey(c);
    const cur = getCollectionPrefs(rowKey).coverSteamIndex ?? -1;
    if (cur < 0) return;
    const next = cur - 1;
    if (next < 0) {
      patchCollectionPrefs(rowKey, { coverSteamIndex: -1 });
      setGridCovers((prev) => ({ ...prev, [rowKey]: undefined }));
      setPrefsRev((n) => n + 1);
      return;
    }
    const url = await fetchCollectionGridCoverUrl(session, c, next);
    if (!url) return;
    patchCollectionPrefs(rowKey, { coverSteamIndex: next });
    setGridCovers((prev) => ({ ...prev, [rowKey]: url }));
    setPrefsRev((n) => n + 1);
  }, [collectionSettingsTarget, session]);

  const nextCoverSteam = useCallback(async () => {
    const c = collectionSettingsTarget;
    if (!c || !isTauri()) return;
    const key = getSteamGridDbApiKey()?.trim();
    if (!key) return;
    const rowKey = collectionRowKey(c);
    const cur = getCollectionPrefs(rowKey).coverSteamIndex ?? -1;
    const next = cur + 1;
    const url = await fetchCollectionGridCoverUrl(session, c, next);
    if (!url) return;
    patchCollectionPrefs(rowKey, { coverSteamIndex: next });
    setGridCovers((prev) => ({ ...prev, [rowKey]: url }));
    setPrefsRev((n) => n + 1);
  }, [collectionSettingsTarget, session]);

  const clearCoverSteam = useCallback(() => {
    const c = collectionSettingsTarget;
    if (!c) return;
    const rowKey = collectionRowKey(c);
    patchCollectionPrefs(rowKey, { coverSteamIndex: -1 });
    setGridCovers((prev) => ({ ...prev, [rowKey]: undefined }));
    setPrefsRev((n) => n + 1);
  }, [collectionSettingsTarget]);

  const prevGameBackgroundSteam = useCallback(async () => {
    const game = gameSettingsTarget;
    if (!game || !isTauri()) return;
    const key = getSteamGridDbApiKey()?.trim();
    if (!key) return;
    const cur = getGamePrefs(game.key, game.name).backgroundSteamIndex ?? -1;
    if (cur < 0) return;
    const next = cur - 1;
    if (next < 0) {
      patchGamePrefs(
        game.key,
        {
          backgroundSteamIndex: -1,
          backgroundSteamUrl: undefined,
        },
        game.name,
      );
      setGameHeroBg({ key: game.key, url: undefined });
      setPrefsRev((n) => n + 1);
      return;
    }
    const url = await fetchGameSteamGridBackgroundUrl(game, next);
    patchGamePrefs(
      game.key,
      {
        backgroundSteamIndex: url ? next : -1,
        backgroundSteamUrl: url ?? undefined,
      },
      game.name,
    );
    setGameHeroBg({ key: game.key, url: url ?? undefined });
    setPrefsRev((n) => n + 1);
  }, [gameSettingsTarget]);

  const nextGameBackgroundSteam = useCallback(async () => {
    const game = gameSettingsTarget;
    if (!game || !isTauri()) return;
    const key = getSteamGridDbApiKey()?.trim();
    if (!key) return;
    const cur = getGamePrefs(game.key, game.name).backgroundSteamIndex ?? -1;
    const next = cur + 1;
    const url = await fetchGameSteamGridBackgroundUrl(game, next);
    patchGamePrefs(
      game.key,
      {
        backgroundSteamIndex: url ? next : -1,
        backgroundSteamUrl: url ?? undefined,
      },
      game.name,
    );
    setGameHeroBg({ key: game.key, url: url ?? undefined });
    setPrefsRev((n) => n + 1);
  }, [gameSettingsTarget]);

  const clearGameBackgroundSteam = useCallback(() => {
    const game = gameSettingsTarget;
    if (!game) return;
    patchGamePrefs(
      game.key,
      {
        backgroundSteamIndex: -1,
        backgroundSteamUrl: undefined,
      },
      game.name,
    );
    setGameHeroBg({ key: game.key, url: undefined });
    setPrefsRev((n) => n + 1);
  }, [gameSettingsTarget]);

  const prevGameCoverSteam = useCallback(async () => {
    const game = gameSettingsTarget;
    if (!game || !isTauri()) return;
    const key = getSteamGridDbApiKey()?.trim();
    if (!key) return;
    const cur = getGamePrefs(game.key, game.name).coverSteamIndex ?? -1;
    if (cur < 0) return;
    const next = cur - 1;
    if (next < 0) {
      patchGamePrefs(game.key, { coverSteamIndex: -1 }, game.name);
      setPrefsRev((n) => n + 1);
      return;
    }
    const url = await fetchGameSteamGridCoverUrl(game, next);
    patchGamePrefs(
      game.key,
      {
        coverSteamIndex: url ? next : -1,
      },
      game.name,
    );
    setPrefsRev((n) => n + 1);
  }, [gameSettingsTarget]);

  const nextGameCoverSteam = useCallback(async () => {
    const game = gameSettingsTarget;
    if (!game || !isTauri()) return;
    const key = getSteamGridDbApiKey()?.trim();
    if (!key) return;
    const cur = getGamePrefs(game.key, game.name).coverSteamIndex ?? -1;
    const next = cur + 1;
    const url = await fetchGameSteamGridCoverUrl(game, next);
    patchGamePrefs(
      game.key,
      {
        coverSteamIndex: url ? next : -1,
      },
      game.name,
    );
    setPrefsRev((n) => n + 1);
  }, [gameSettingsTarget]);

  const clearGameCoverSteam = useCallback(() => {
    const game = gameSettingsTarget;
    if (!game) return;
    patchGamePrefs(game.key, { coverSteamIndex: -1 }, game.name);
    setPrefsRev((n) => n + 1);
  }, [gameSettingsTarget]);

  const activateCollectionSettingsNav = useCallback(() => {
    const c = collectionSettingsTarget;
    if (!c) return;
    const rowKey = collectionRowKey(c);
    switch (collectionSettingsNavIndex) {
      case 0: {
        const h = getCollectionPrefs(rowKey).hidden;
        patchCollectionPrefs(rowKey, { hidden: !h });
        setPrefsRev((n) => n + 1);
        break;
      }
      case 1:
        void prevHeroSteam();
        break;
      case 2:
        void nextHeroSteam();
        break;
      case 3:
        clearHeroSteam();
        break;
      case 4:
        void prevCoverSteam();
        break;
      case 5:
        void nextCoverSteam();
        break;
      case 6:
        clearCoverSteam();
        break;
      default:
        break;
    }
  }, [
    collectionSettingsNavIndex,
    collectionSettingsTarget,
    clearCoverSteam,
    clearHeroSteam,
    nextCoverSteam,
    nextHeroSteam,
    prevCoverSteam,
    prevHeroSteam,
  ]);

  const activateGameSettingsNav = useCallback(() => {
    switch (gameSettingsNavIndex) {
      case 0:
        void prevGameBackgroundSteam();
        break;
      case 1:
        void nextGameBackgroundSteam();
        break;
      case 2:
        clearGameBackgroundSteam();
        break;
      case 3:
        void prevGameCoverSteam();
        break;
      case 4:
        void nextGameCoverSteam();
        break;
      case 5:
        clearGameCoverSteam();
        break;
      default:
        break;
    }
  }, [
    clearGameBackgroundSteam,
    clearGameCoverSteam,
    gameSettingsNavIndex,
    nextGameBackgroundSteam,
    nextGameCoverSteam,
    prevGameBackgroundSteam,
    prevGameCoverSteam,
  ]);

  useLayoutEffect(() => {
    if (!settingsOpen) return;
    const refs = [
      settingsRadioCollectionRef,
      settingsRadioFranchiseRef,
      settingsSteamKeyRef,
      settingsSaveRef,
      settingsUnhideAllRef,
    ] as const;
    const el = refs[settingsNavIndex]?.current;
    el?.focus();
  }, [settingsOpen, settingsNavIndex]);

  useLayoutEffect(() => {
    if (!collectionSettingsOpen) return;
    const refs = [
      collectionHideRef,
      collectionPrevHeroRef,
      collectionNextHeroRef,
      collectionClearHeroRef,
      collectionPrevCoverRef,
      collectionNextCoverRef,
      collectionClearCoverRef,
    ] as const;
    refs[collectionSettingsNavIndex]?.current?.focus();
  }, [collectionSettingsOpen, collectionSettingsNavIndex]);

  useLayoutEffect(() => {
    if (!gameSettingsOpen) return;
    const refs = [
      gamePrevHeroRef,
      gameNextHeroRef,
      gameClearHeroRef,
      gamePrevCoverRef,
      gameNextCoverRef,
      gameClearCoverRef,
    ] as const;
    refs[gameSettingsNavIndex]?.current?.focus();
  }, [gameSettingsOpen, gameSettingsNavIndex]);

  function selectVirtualType(next: VirtualCollectionType) {
    saveVirtualCollectionType(next);
    setVirtualType(next);
  }

  useEffect(() => {
    if (currentLoading || currentCards.length === 0) return;
    const el = carouselViewportRef.current;
    if (!el) return;
    const apply = () => {
      const t = carouselViewportRef.current;
      if (t) {
        setSlotRadius(computeCarouselSlotRadius(t.getBoundingClientRect().width));
      }
    };
    apply();
    const ro = new ResizeObserver(() => apply());
    ro.observe(el);
    window.addEventListener("resize", apply);
    return () => {
      ro.disconnect();
      window.removeEventListener("resize", apply);
    };
  }, [currentCards.length, currentLoading]);

  /** Keep the focused card’s horizontal center aligned with the viewport center. */
  useLayoutEffect(() => {
    const vp = carouselViewportRef.current;
    const track = carouselTrackRef.current;
    const focusEl = focusSlotRef.current;
    if (!vp || !track || !focusEl || currentLoading || currentCards.length === 0) {
      if (track) track.style.transform = "translateX(0)";
      return;
    }

    const align = (instant: boolean) => {
      if (instant) track.style.transition = "none";
      const vr = vp.getBoundingClientRect();
      const fr = focusEl.getBoundingClientRect();
      const viewportCx = vr.left + vr.width / 2;
      const focusCx = fr.left + fr.width / 2;
      const delta = viewportCx - focusCx;
      const ct = getComputedStyle(track).transform;
      let curTx = 0;
      if (ct && ct !== "none") {
        curTx = new DOMMatrix(ct).m41;
      }
      track.style.transform = `translateX(${curTx + delta}px)`;
      if (instant) {
        void track.offsetWidth;
        track.style.removeProperty("transition");
      }
    };

    align(false);
    const ro = new ResizeObserver(() => requestAnimationFrame(() => align(true)));
    ro.observe(vp);
    ro.observe(track);
    return () => ro.disconnect();
  }, [currentFocusIndex, currentCards.length, currentLoading, refreshing, slotRadius]);

  const focusedCollection =
    !inGamesView && visibleItems.length > 0 ? visibleItems[focusIndex] : undefined;
  const focusedGame =
    inGamesView && games.length > 0 ? games[gamesFocusIndex] : undefined;
  const defaultFocusedGameBgUrl =
    focusedGame?.backgroundUrl ?? focusedGame?.coverUrl;
  const cardCoverUrl = useMemo(() => {
    if (focusedCollection) {
      return coverForCarouselSlot(session.apiBase, focusedCollection, gridCovers);
    }
    return focusedGame
      ? coverForGameCarouselSlot(focusedGame, gameGridCovers)
      : undefined;
  }, [
    focusedCollection,
    focusedGame,
    session.apiBase,
    gridCovers,
    gameGridCovers,
    prefsRev,
  ]);

  const [heroBg, setHeroBg] = useState<{
    key: string;
    url: string | undefined;
  } | null>(null);
  const [gameHeroBg, setGameHeroBg] = useState<{
    key: string;
    url: string | undefined;
  } | null>(null);

  useEffect(() => {
    if (!focusedCollection) {
      setHeroBg(null);
      return;
    }
    const key = collectionRowKey(focusedCollection);
    const cover = coverForCarouselSlot(
      session.apiBase,
      focusedCollection,
      gridCovers,
    );
    const heroIdx =
      getCollectionPrefs(collectionRowKey(focusedCollection)).heroSteamIndex ?? -1;
    setHeroBg({ key, url: undefined });

    let cancelled = false;
    void (async () => {
      const url = await fetchCollectionBackgroundUrl(
        session,
        focusedCollection,
        cover,
        heroIdx,
      );
      if (cancelled) return;
      setHeroBg({ key, url: url ?? undefined });
    })();

    return () => {
      cancelled = true;
    };
  }, [
    focusedCollection,
    session.apiBase,
    session.accessToken,
    steamSettingsRev,
    prefsRev,
    gridCovers,
  ]);

  useEffect(() => {
    if (!focusedGame) {
      setGameHeroBg(null);
      return;
    }

    const key = focusedGame.key;
    const gamePrefs = getGamePrefs(focusedGame.key, focusedGame.name);
    const heroIdx = gamePrefs.backgroundSteamIndex ?? -1;
    if (heroIdx < 0) {
      setGameHeroBg({ key, url: undefined });
      return;
    }

    if (gamePrefs.backgroundSteamUrl) {
      setGameHeroBg({ key, url: gamePrefs.backgroundSteamUrl });
      return;
    }

    const cached = getCachedGameSteamGridBackgroundUrl(focusedGame, heroIdx);
    setGameHeroBg({ key, url: cached });

    if (cached) return;

    let cancelled = false;
    void (async () => {
      const url = await fetchGameSteamGridBackgroundUrl(focusedGame, heroIdx);
      if (cancelled) return;
      setGameHeroBg({ key, url: url ?? undefined });
    })();

    return () => {
      cancelled = true;
    };
  }, [focusedGame, steamSettingsRev, prefsRev]);

  const bgUrl = inGamesView
    ? focusedGame
      ? gameHeroBg &&
          gameHeroBg.key === focusedGame.key &&
          gameHeroBg.url
        ? gameHeroBg.url
        : defaultFocusedGameBgUrl
      : undefined
    : focusedCollection &&
        heroBg &&
        heroBg.key === collectionRowKey(focusedCollection)
      ? (heroBg.url ?? cardCoverUrl)
      : cardCoverUrl;
  const bgLayerIdRef = useRef(0);
  const bgFadeTimeoutRef = useRef<number | null>(null);
  const bgActivateFrameRef = useRef<number | null>(null);
  const [bgLayers, setBgLayers] = useState<BackgroundLayer[]>(() =>
    bgUrl ? [{ id: 0, url: bgUrl, active: true }] : [],
  );

  useEffect(() => {
    if (!bgUrl) return;

    const normalizedBgUrl = bgUrl;

    if (bgFadeTimeoutRef.current !== null) {
      window.clearTimeout(bgFadeTimeoutRef.current);
      bgFadeTimeoutRef.current = null;
    }
    if (bgActivateFrameRef.current !== null) {
      window.cancelAnimationFrame(bgActivateFrameRef.current);
      bgActivateFrameRef.current = null;
    }

    setBgLayers((prev) => {
      const latest = prev[prev.length - 1];
      const latestUrl = latest?.url;
      if (latestUrl === normalizedBgUrl) {
        if (prev.length <= 1) return prev;
        return latest ? [{ ...latest, active: true }] : prev;
      }

      const nextLayer: BackgroundLayer = {
        id: ++bgLayerIdRef.current,
        url: normalizedBgUrl,
        active: false,
      };
      if (prev.length === 0) return [{ ...nextLayer, active: true }];
      return [{ ...prev[prev.length - 1], active: true }, nextLayer];
    });

    bgActivateFrameRef.current = window.requestAnimationFrame(() => {
      bgActivateFrameRef.current = window.requestAnimationFrame(() => {
        setBgLayers((prev) => {
          if (prev.length <= 1) return prev;
          return prev.map((layer, index) => ({
            ...layer,
            active: index === prev.length - 1,
          }));
        });
        bgActivateFrameRef.current = null;
        bgFadeTimeoutRef.current = window.setTimeout(() => {
          setBgLayers((prev) => {
            if (prev.length <= 1) return prev;
            const latest = prev[prev.length - 1];
            return latest ? [{ ...latest, active: true }] : prev;
          });
          bgFadeTimeoutRef.current = null;
        }, BACKGROUND_CROSSFADE_MS);
      });
    });
  }, [bgUrl]);

  useEffect(() => {
    return () => {
      if (bgFadeTimeoutRef.current !== null) {
        window.clearTimeout(bgFadeTimeoutRef.current);
      }
      if (bgActivateFrameRef.current !== null) {
        window.cancelAnimationFrame(bgActivateFrameRef.current);
      }
    };
  }, []);

  const moveFocus = useCallback(
    (delta: number) => {
      if (currentCards.length === 0) return;
      const n = currentCards.length;
      const from = focusIndexRef.current;
      const next = (from + delta + n) % n;
      focusIndexRef.current = next;
      if (activeCollection) {
        setGamesFocusIndex(next);
      } else {
        setFocusIndex(next);
      }
    },
    [activeCollection, currentCards.length],
  );

  const hintsReady = !currentLoading;
  const showMoveHints = hintsReady && currentCards.length > 0;
  const itemSettingsOpen = collectionSettingsOpen || gameSettingsOpen;
  const itemSettingsNav = collectionSettingsOpen
    ? {
        slotCount: COLLECTION_SETTINGS_NAV_SLOTS,
        setFocusIndex: setCollectionSettingsNavIndex,
        onActivate: activateCollectionSettingsNav,
        onCloseSettings: closeCollectionSettings,
      }
    : gameSettingsOpen
      ? {
          slotCount: GAME_SETTINGS_NAV_SLOTS,
          setFocusIndex: setGameSettingsNavIndex,
          onActivate: activateGameSettingsNav,
          onCloseSettings: closeCollectionSettings,
        }
      : null;

  useCollectionsGamepadNavigation({
    enabled: tauriShell && hintsReady,
    itemsLength: currentCards.length,
    collectionSettingsOpen: itemSettingsOpen,
    collectionSettingsNav: itemSettingsNav,
    settingsOpen,
    settingsNav: settingsOpen
      ? {
          slotCount: SETTINGS_NAV_SLOTS,
          setFocusIndex: setSettingsNavIndex,
          onActivate: activateSettingsNav,
          onCloseSettings: () => setSettingsOpen(false),
        }
      : null,
    refreshDisabled: currentLoading || refreshing,
    onMove: moveFocus,
    onBack: goBack,
    onPrimaryAction: activeCollection ? null : openGamesView,
    onToggleSettings: toggleSettings,
    onToggleCollectionSettings: toggleCollectionSettings,
    onRefresh: () => void onRefreshLibrary(),
  });

  useEffect(() => {
    function isShortcutTarget(el: EventTarget | null): boolean {
      if (!el || !(el instanceof HTMLElement)) return false;
      const tag = el.tagName;
      if (tag === "INPUT" || tag === "TEXTAREA" || tag === "SELECT") {
        return true;
      }
      return el.isContentEditable;
    }

    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") {
        if (itemSettingsOpen) {
          e.preventDefault();
          closeCollectionSettings();
          return;
        }
        if (settingsOpen) {
          e.preventDefault();
          setSettingsOpen(false);
          return;
        }
        e.preventDefault();
        goBack();
        return;
      }

      if (!isShortcutTarget(e.target)) {
        if (e.key === "o" || e.key === "O") {
          e.preventDefault();
          toggleSettings();
          return;
        }
        if ((e.key === "i" || e.key === "I") && !settingsOpen) {
          e.preventDefault();
          toggleCollectionSettings();
          return;
        }
        if (
          (e.key === "r" || e.key === "R") &&
          !currentLoading &&
          !refreshing
        ) {
          e.preventDefault();
          void onRefreshLibrary();
          return;
        }
        if (
          e.key === "Enter" &&
          !e.repeat &&
          !itemSettingsOpen &&
          !activeCollection &&
          visibleItems.length > 0
        ) {
          e.preventDefault();
          openGamesView();
          return;
        }
      }

      if (itemSettingsOpen) {
        if (e.key === "ArrowUp") {
          e.preventDefault();
          if (collectionSettingsOpen) {
            setCollectionSettingsNavIndex((i) => Math.max(0, i - 1));
          } else {
            setGameSettingsNavIndex((i) => Math.max(0, i - 1));
          }
          return;
        }
        if (e.key === "ArrowDown") {
          e.preventDefault();
          if (collectionSettingsOpen) {
            setCollectionSettingsNavIndex((i) =>
              Math.min(COLLECTION_SETTINGS_NAV_SLOTS - 1, i + 1),
            );
          } else {
            setGameSettingsNavIndex((i) =>
              Math.min(GAME_SETTINGS_NAV_SLOTS - 1, i + 1),
            );
          }
          return;
        }
        if (e.key === "Enter" && !e.repeat) {
          e.preventDefault();
          if (collectionSettingsOpen) {
            activateCollectionSettingsNav();
          } else {
            activateGameSettingsNav();
          }
          return;
        }
        if (e.key === "ArrowLeft" || e.key === "ArrowRight") {
          e.preventDefault();
          return;
        }
        if (e.key === "Backspace" && !isShortcutTarget(e.target)) {
          e.preventDefault();
          return;
        }
        return;
      }

      if (settingsOpen) {
        if (e.key === "ArrowUp") {
          e.preventDefault();
          setSettingsNavIndex((i) => Math.max(0, i - 1));
          return;
        }
        if (e.key === "ArrowDown") {
          e.preventDefault();
          setSettingsNavIndex((i) =>
            Math.min(SETTINGS_NAV_SLOTS - 1, i + 1),
          );
          return;
        }
        if (e.key === "Enter" && !e.repeat) {
          if (e.target instanceof HTMLTextAreaElement) return;
          e.preventDefault();
          activateSettingsNav();
          return;
        }
        if (e.key === "ArrowLeft" || e.key === "ArrowRight") {
          e.preventDefault();
          return;
        }
        if (e.key === "Backspace" && !isShortcutTarget(e.target)) {
          e.preventDefault();
          return;
        }
        return;
      }

      if (e.key === "ArrowLeft") {
        e.preventDefault();
        moveFocus(-1);
      } else if (e.key === "ArrowRight") {
        e.preventDefault();
        moveFocus(1);
      } else if (e.key === "Backspace") {
        e.preventDefault();
        goBack();
      }
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [
    activeCollection,
    moveFocus,
    goBack,
    currentLoading,
    onRefreshLibrary,
    settingsOpen,
    collectionSettingsOpen,
    gameSettingsOpen,
    itemSettingsOpen,
    toggleSettings,
    toggleCollectionSettings,
    closeCollectionSettings,
    openGamesView,
    visibleItems.length,
    activateSettingsNav,
    activateCollectionSettingsNav,
    activateGameSettingsNav,
    refreshing,
  ]);

  const slots = useMemo(() => {
    const r = slotRadius;
    const len = r * 2 + 1;
    return Array.from({ length: len }, (_, i) => i - r);
  }, [slotRadius]);
  const timelineVisibleStartIndex =
    activeCollection !== null ? Math.max(0, currentFocusIndex - slotRadius) : -1;
  const timelineVisibleEndIndex =
    activeCollection !== null
      ? Math.min(currentCards.length - 1, currentFocusIndex + slotRadius)
      : -1;
  const timelineVisibleCount =
    activeCollection !== null &&
    timelineVisibleStartIndex >= 0 &&
    timelineVisibleEndIndex >= timelineVisibleStartIndex
      ? timelineVisibleEndIndex - timelineVisibleStartIndex + 1
      : 0;
  const timelineStartSlot =
    activeCollection !== null && timelineVisibleStartIndex >= 0
      ? timelineVisibleStartIndex - currentFocusIndex + slotRadius
      : -1;
  const sharedTimelineStyle =
    timelineVisibleCount > 0 && timelineStartSlot >= 0
      ? ({
          ["--timeline-start-slot" as string]: String(timelineStartSlot),
          ["--timeline-slot-count" as string]: String(timelineVisibleCount),
        } as CSSProperties)
      : undefined;

  const headerTitle = activeCollection ? "GAMES" : "COLLECTIONS";
  const headerSubtitle = activeCollection
    ? `Browse games in ${activeCollection.name}`
    : "Browse your game collections";
  const backLabel = activeCollection ? "Back to collections" : "Back to login";
  const itemSettingsLabel = activeCollection
    ? "Game settings"
    : "Collection settings";

  const settingsPortal =
    settingsOpen && typeof document !== "undefined"
      ? createPortal(
          <>
            <div
              className="collections-settings-backdrop"
              aria-hidden
              onPointerDown={() => setSettingsOpen(false)}
            />
            <div
              ref={settingsWrapRef}
              id="collections-settings-menu"
              className="collections-settings-menu collections-settings-menu--popover"
              role="dialog"
              aria-label="Launcher settings"
              aria-modal="true"
              onPointerDown={(e) => e.stopPropagation()}
            >
              <p className="collections-settings-menu-title">
                Autogenerated groups
              </p>
              <p className="collections-settings-menu-hint">
                Same option as RomM’s virtual collection type (IGDB metadata).
              </p>
              <label
                className={`collections-settings-option${settingsNavIndex === 0 ? " collections-settings-option--active" : ""}`}
              >
                <input
                  ref={settingsRadioCollectionRef}
                  type="radio"
                  name="virtual-type"
                  checked={virtualType === "collection"}
                  onChange={() => selectVirtualType("collection")}
                  onFocus={() => setSettingsNavIndex(0)}
                />
                <span>
                  <strong>IGDB collection</strong>
                  <span className="collections-settings-option-desc">
                    Series / collection names from IGDB (RomM default).
                  </span>
                </span>
              </label>
              <label
                className={`collections-settings-option${settingsNavIndex === 1 ? " collections-settings-option--active" : ""}`}
              >
                <input
                  ref={settingsRadioFranchiseRef}
                  type="radio"
                  name="virtual-type"
                  checked={virtualType === "franchise"}
                  onChange={() => selectVirtualType("franchise")}
                  onFocus={() => setSettingsNavIndex(1)}
                />
                <span>
                  <strong>Franchise</strong>
                  <span className="collections-settings-option-desc">
                    Group by franchise (e.g. Super Mario).
                  </span>
                </span>
              </label>
              <div className="collections-settings-steamgrid">
                <p className="collections-settings-menu-title collections-settings-menu-title--spaced">
                  SteamGridDB backgrounds
                </p>
                <p className="collections-settings-menu-hint">
                  Optional API key for hero-style backdrop art (
                  <a
                    href="https://www.steamgriddb.com/profile/preferences"
                    target="_blank"
                    rel="noreferrer"
                  >
                    create a key
                  </a>
                  ). Stored only on this device. If empty, RomM screenshots are
                  used instead.
                </p>
                <input
                  ref={settingsSteamKeyRef}
                  type="password"
                  className={`collections-settings-steamgrid-input${settingsNavIndex === 2 ? " collections-settings-steamgrid-input--active" : ""}`}
                  autoComplete="off"
                  placeholder="API key"
                  value={steamGridKeyDraft}
                  onChange={(e) => setSteamGridKeyDraft(e.target.value)}
                  onFocus={() => setSettingsNavIndex(2)}
                />
                <button
                  ref={settingsSaveRef}
                  type="button"
                  className={`collections-settings-steamgrid-save${settingsNavIndex === 3 ? " collections-settings-steamgrid-save--active" : ""}`}
                  onClick={saveSteamGridKey}
                  onFocus={() => setSettingsNavIndex(3)}
                >
                  Save key
                </button>
                <button
                  ref={settingsUnhideAllRef}
                  type="button"
                  className={`collections-settings-steamgrid-save${settingsNavIndex === 4 ? " collections-settings-steamgrid-save--active" : ""}`}
                  onClick={onUnhideAllCollections}
                  onFocus={() => setSettingsNavIndex(4)}
                >
                  Unhide all collections
                </button>
              </div>
            </div>
          </>,
          document.body,
        )
      : null;

  const collSteamDisabled =
    !isTauri() || !getSteamGridDbApiKey()?.trim();
  const gameSteamDisabled = collSteamDisabled;

  const collectionSettingsPortal =
    collectionSettingsOpen &&
    collectionSettingsTarget &&
    typeof document !== "undefined"
      ? createPortal(
          <>
            <div
              className="collections-settings-backdrop"
              aria-hidden
              onPointerDown={() => closeCollectionSettings()}
            />
            <div
              className="collections-settings-menu collections-settings-menu--popover"
              role="dialog"
              aria-label="Collection settings"
              aria-modal="true"
              onPointerDown={(e) => e.stopPropagation()}
            >
              <p className="collections-settings-menu-title">
                Collection settings
              </p>
              <p className="collections-settings-menu-hint">
                {collectionSettingsTarget.name}
              </p>
              <button
                ref={collectionHideRef}
                type="button"
                className={`collections-settings-action${collectionSettingsNavIndex === 0 ? " collections-settings-action--active" : ""}`}
                onFocus={() => setCollectionSettingsNavIndex(0)}
                onClick={() => {
                  const c = collectionSettingsTarget;
                  if (!c) return;
                  const rowKey = collectionRowKey(c);
                  const h = getCollectionPrefs(rowKey).hidden;
                  patchCollectionPrefs(rowKey, { hidden: !h });
                  setPrefsRev((n) => n + 1);
                }}
              >
                <strong>
                  {getCollectionPrefs(collectionRowKey(collectionSettingsTarget))
                    .hidden
                    ? "Show in launcher"
                    : "Hide from launcher"}
                </strong>
              </button>
              <button
                ref={collectionPrevHeroRef}
                type="button"
                className={`collections-settings-action${collectionSettingsNavIndex === 1 ? " collections-settings-action--active" : ""}${collSteamDisabled ? " collections-settings-action--disabled" : ""}`}
                onFocus={() => setCollectionSettingsNavIndex(1)}
                onClick={() => void prevHeroSteam()}
              >
                <strong>Previous SteamGrid background</strong>
              </button>
              <button
                ref={collectionNextHeroRef}
                type="button"
                className={`collections-settings-action${collectionSettingsNavIndex === 2 ? " collections-settings-action--active" : ""}${collSteamDisabled ? " collections-settings-action--disabled" : ""}`}
                onFocus={() => setCollectionSettingsNavIndex(2)}
                onClick={() => void nextHeroSteam()}
              >
                <strong>Next SteamGrid background</strong>
              </button>
              <button
                ref={collectionClearHeroRef}
                type="button"
                className={`collections-settings-action${collectionSettingsNavIndex === 3 ? " collections-settings-action--active" : ""}${collSteamDisabled ? " collections-settings-action--disabled" : ""}`}
                onFocus={() => setCollectionSettingsNavIndex(3)}
                onClick={clearHeroSteam}
              >
                <strong>Clear SteamGrid background</strong>
              </button>
              <button
                ref={collectionPrevCoverRef}
                type="button"
                className={`collections-settings-action${collectionSettingsNavIndex === 4 ? " collections-settings-action--active" : ""}${collSteamDisabled ? " collections-settings-action--disabled" : ""}`}
                onFocus={() => setCollectionSettingsNavIndex(4)}
                onClick={() => void prevCoverSteam()}
              >
                <strong>Previous cover art</strong>
              </button>
              <button
                ref={collectionNextCoverRef}
                type="button"
                className={`collections-settings-action${collectionSettingsNavIndex === 5 ? " collections-settings-action--active" : ""}${collSteamDisabled ? " collections-settings-action--disabled" : ""}`}
                onFocus={() => setCollectionSettingsNavIndex(5)}
                onClick={() => void nextCoverSteam()}
              >
                <strong>Next cover art</strong>
              </button>
              <button
                ref={collectionClearCoverRef}
                type="button"
                className={`collections-settings-action${collectionSettingsNavIndex === 6 ? " collections-settings-action--active" : ""}${collSteamDisabled ? " collections-settings-action--disabled" : ""}`}
                onFocus={() => setCollectionSettingsNavIndex(6)}
                onClick={clearCoverSteam}
              >
                <strong>Clear cover art</strong>
              </button>
            </div>
          </>,
          document.body,
        )
      : null;

  const gameSettingsPortal =
    gameSettingsOpen &&
    gameSettingsTarget &&
    typeof document !== "undefined"
      ? createPortal(
          <>
            <div
              className="collections-settings-backdrop"
              aria-hidden
              onPointerDown={() => closeCollectionSettings()}
            />
            <div
              className="collections-settings-menu collections-settings-menu--popover"
              role="dialog"
              aria-label="Game settings"
              aria-modal="true"
              onPointerDown={(e) => e.stopPropagation()}
            >
              <p className="collections-settings-menu-title">Game settings</p>
              <p className="collections-settings-menu-hint">
                {gameSettingsTarget.name}
              </p>
              <button
                ref={gamePrevHeroRef}
                type="button"
                className={`collections-settings-action${gameSettingsNavIndex === 0 ? " collections-settings-action--active" : ""}${gameSteamDisabled ? " collections-settings-action--disabled" : ""}`}
                onFocus={() => setGameSettingsNavIndex(0)}
                onClick={() => void prevGameBackgroundSteam()}
              >
                <strong>Previous SteamGrid background</strong>
              </button>
              <button
                ref={gameNextHeroRef}
                type="button"
                className={`collections-settings-action${gameSettingsNavIndex === 1 ? " collections-settings-action--active" : ""}${gameSteamDisabled ? " collections-settings-action--disabled" : ""}`}
                onFocus={() => setGameSettingsNavIndex(1)}
                onClick={() => void nextGameBackgroundSteam()}
              >
                <strong>Next SteamGrid background</strong>
              </button>
              <button
                ref={gameClearHeroRef}
                type="button"
                className={`collections-settings-action${gameSettingsNavIndex === 2 ? " collections-settings-action--active" : ""}`}
                onFocus={() => setGameSettingsNavIndex(2)}
                onClick={clearGameBackgroundSteam}
              >
                <strong>Clear SteamGrid background</strong>
              </button>
              <button
                ref={gamePrevCoverRef}
                type="button"
                className={`collections-settings-action${gameSettingsNavIndex === 3 ? " collections-settings-action--active" : ""}${gameSteamDisabled ? " collections-settings-action--disabled" : ""}`}
                onFocus={() => setGameSettingsNavIndex(3)}
                onClick={() => void prevGameCoverSteam()}
              >
                <strong>Previous cover art</strong>
              </button>
              <button
                ref={gameNextCoverRef}
                type="button"
                className={`collections-settings-action${gameSettingsNavIndex === 4 ? " collections-settings-action--active" : ""}${gameSteamDisabled ? " collections-settings-action--disabled" : ""}`}
                onFocus={() => setGameSettingsNavIndex(4)}
                onClick={() => void nextGameCoverSteam()}
              >
                <strong>Next cover art</strong>
              </button>
              <button
                ref={gameClearCoverRef}
                type="button"
                className={`collections-settings-action${gameSettingsNavIndex === 5 ? " collections-settings-action--active" : ""}`}
                onFocus={() => setGameSettingsNavIndex(5)}
                onClick={clearGameCoverSteam}
              >
                <strong>Clear cover art</strong>
              </button>
            </div>
          </>,
          document.body,
        )
      : null;

  return (
    <div
      className="collections-screen"
    >
      {settingsPortal}
      {collectionSettingsPortal}
      {gameSettingsPortal}

      <div className="collections-bg-stack" aria-hidden>
        {bgLayers.length > 0 ? (
          bgLayers.map((layer) => (
            <div
              key={layer.id}
              className={`collections-bg${layer.active ? " collections-bg--active" : " collections-bg--inactive"}`}
              style={backgroundImageStyle(layer.url)}
            />
          ))
        ) : (
          <div className="collections-bg collections-bg--active" />
        )}
      </div>
      <div className="collections-bg-scrim" />

      <header className="collections-header">
        <h1 className="collections-title">{headerTitle}</h1>
        <p className="collections-subtitle">{headerSubtitle}</p>
      </header>

      {currentLoading ? (
        <p className="collections-status">
          {activeCollection ? "Loading games…" : "Loading collections…"}
        </p>
      ) : null}
      {currentError ? (
        <p className="collections-error" role="alert">
          {currentError}
        </p>
      ) : null}

      {!currentLoading && !currentError && !activeCollection && items.length === 0 ? (
        <p className="collections-status">
          No collections found. Add manual or smart collections in RomM, or
          enable autogenerated groups in library settings—then log in again.
        </p>
      ) : null}

      {!currentLoading &&
      !currentError &&
      !activeCollection &&
      items.length > 0 &&
      visibleItems.length === 0 ? (
        <p className="collections-status">
          Every collection is hidden. Clear this launcher’s saved preferences
          (for example the <code>romm-launcher-collection-prefs-v1</code>{" "}
          localStorage key) and reload to show collections again.
        </p>
      ) : null}

      {!currentLoading && !currentError && activeCollection && games.length === 0 ? (
        <p className="collections-status">
          No games found in <strong>{activeCollection.name}</strong>.
        </p>
      ) : null}

      {!currentLoading && currentCards.length > 0 ? (
        <div
          className="collections-carousel-viewport"
          ref={carouselViewportRef}
        >
          <div
            className="collections-carousel-track"
            ref={carouselTrackRef}
            role="list"
          >
            {activeCollection && sharedTimelineStyle ? (
              <span
                className="collections-shared-timeline"
                style={sharedTimelineStyle}
                aria-hidden
              />
            ) : null}
            {slots.map((offset) => {
              const idx = currentFocusIndex + offset;
              const card = currentCards[idx];
              const isFocus = offset === 0;
              const isPlaceholder = idx < 0 || idx >= currentCards.length;
              const edgeClass =
                slots.length > 1
                  ? offset === -slotRadius
                    ? " collection-slot--edge-start"
                    : offset === slotRadius
                      ? " collection-slot--edge-end"
                      : ""
                  : "";

              if (isPlaceholder) {
                return (
                  <div
                    key={`empty-${offset}`}
                    className={`collection-slot collection-slot--empty${edgeClass}`}
                    aria-hidden
                  >
                    <div className="collection-poster collection-poster--empty" />
                    <div
                      className={`collection-meta${
                        activeCollection
                          ? " collection-meta--timeline-placeholder"
                          : ""
                      }`}
                    >
                      <span className="collection-years"> </span>
                      <span className="collection-label"> </span>
                    </div>
                  </div>
                );
              }

              const slideClass = carouselSlotContentAnimClass(carouselTransition, {
                idx,
                offset,
                isFocus,
                isPlaceholder: false,
                slotRadius,
              });
              return (
                <button
                  key={`${card.key}-${idx}`}
                  ref={isFocus ? focusSlotRef : undefined}
                  type="button"
                  role="listitem"
                  className={`collection-slot${isFocus ? " collection-slot--focus" : ""}${
                    card.showTimeline ? " collection-slot--timeline" : ""
                  }${edgeClass}`}
                  onClick={() => {
                    const cur = focusIndexRef.current;
                    if (idx === cur) {
                      if (!activeCollection) openGamesView();
                      return;
                    }
                    focusIndexRef.current = idx;
                    if (activeCollection) {
                      setGamesFocusIndex(idx);
                    } else {
                      setFocusIndex(idx);
                    }
                  }}
                >
                  <div className="collection-slot-content">
                    <div className={`collection-slot-poster-wrap${slideClass}`}>
                      <div
                        className={`collection-poster${isFocus ? " collection-poster--focus" : ""}`}
                      >
                        {card.coverUrl ? (
                          <img src={card.coverUrl} alt="" loading="lazy" />
                        ) : (
                          <span className="collection-poster-fallback">
                            {card.title}
                          </span>
                        )}
                      </div>
                    </div>
                    <div
                      className={`collection-meta${
                        card.showTimeline
                          ? " collection-meta--timeline"
                          : " collection-meta--timeline-placeholder"
                      }`}
                    >
                      {card.showTimeline ? (
                        <span
                          className={`collection-timeline-dot-wrap${slideClass}${
                            isFocus ? " collection-timeline-dot-wrap--focus" : ""
                          }`}
                          aria-hidden
                        >
                          <span
                            className={`collection-timeline-dot${
                              isFocus ? " collection-timeline-dot--focus" : ""
                            }`}
                          />
                        </span>
                      ) : null}
                      <div className={`collection-meta-text${slideClass}`}>
                        <span className="collection-years">{card.meta}</span>
                        <span className="collection-label">{card.title}</span>
                      </div>
                    </div>
                  </div>
                </button>
              );
            })}
          </div>
        </div>
      ) : null}

      {hintsReady ? (
        <footer className="collections-footer" aria-label="Shortcuts">
          {showMoveHints ? (
            <div className="collections-footer-hint">
              {showGamepadHints ? (
                <GamepadHorizontalNavPromptGlyphs flavor={gamepadFlavor} />
              ) : (
                <KeyboardMoveHorizontalGlyph />
              )}
              <span>Move</span>
            </div>
          ) : null}
          {!activeCollection ? (
            <div
              className={`collections-footer-hint${visibleItems.length === 0 ? " collections-footer-hint--disabled" : ""}`}
            >
              {showGamepadHints ? (
                <GamepadPromptGlyph flavor={gamepadFlavor} role="primary" />
              ) : (
                <KeyboardEnterPromptGlyph />
              )}
              <span>Select</span>
            </div>
          ) : null}
          <div
            className={`collections-footer-hint${
              currentCards.length === 0 ? " collections-footer-hint--disabled" : ""
            }`}
          >
            {showGamepadHints ? (
              <GamepadCollectionSettingsPromptGlyph flavor={gamepadFlavor} />
            ) : (
              <KeyboardCollectionSettingsGlyph />
            )}
            <span>{itemSettingsLabel}</span>
          </div>
          <div className="collections-footer-hint">
            {showGamepadHints ? (
              <GamepadStartPromptGlyph flavor={gamepadFlavor} />
            ) : (
              <KeyboardSettingsGlyph />
            )}
            <span>Launcher settings</span>
          </div>
          <div
            className={`collections-footer-hint${currentLoading || refreshing ? " collections-footer-hint--disabled" : ""}`}
          >
            {showGamepadHints ? (
              <GamepadSelectPromptGlyph flavor={gamepadFlavor} />
            ) : (
              <KeyboardRefreshGlyph />
            )}
            <span>{refreshing ? "Refreshing…" : "Refresh library"}</span>
          </div>
          <div className="collections-footer-hint collections-footer-hint--back">
            {showGamepadHints ? (
              <GamepadPromptGlyph flavor={gamepadFlavor} role="back" />
            ) : (
              <KeyboardBackGlyph />
            )}
            <span>{backLabel}</span>
          </div>
        </footer>
      ) : null}
    </div>
  );
}
