import {
  useCallback,
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { invoke } from "@tauri-apps/api/core";
import {
  FETCH_CONCURRENCY,
  fetchReleaseYearLabel,
  mapPool,
} from "./collectionReleaseYears";
import { rommAssetUrl } from "./rommAssets";
import {
  loadVirtualCollectionType,
  saveVirtualCollectionType,
  type VirtualCollectionType,
} from "./virtualCollectionType";
import "./CollectionsView.css";

export type Session = {
  apiBase: string;
  accessToken: string;
};

type RommCollection = {
  /** Numeric for manual/smart collections; base64 string for virtual (autogenerated). */
  id: number | string;
  name: string;
  description?: string;
  rom_count?: number;
  path_cover_small?: string | null;
  path_cover_large?: string | null;
  /** Virtual / autogenerated collections use mosaic paths (RomM API). */
  path_covers_small?: string[] | null;
  path_covers_large?: string[] | null;
  url_cover?: string | null;
  created_at?: string;
  updated_at?: string;
  is_smart?: boolean;
  is_virtual?: boolean;
  /** RomM virtual collection category (e.g. franchise grouping). */
  collection_type?: string;
  /** Member ROM ids (RomM includes this on collection payloads). */
  rom_ids?: number[];
};

type Props = {
  session: Session;
  onLogout: () => void;
};

function formatInvokeError(err: unknown): string {
  if (typeof err === "string") return err;
  if (err instanceof Error) return err.message;
  try {
    return JSON.stringify(err);
  } catch {
    return String(err);
  }
}

function firstCoverUrl(
  apiBase: string,
  paths: string[] | null | undefined,
): string | undefined {
  if (!paths?.length) return undefined;
  return rommAssetUrl(apiBase, paths[0]);
}

function coverForCollection(apiBase: string, c: RommCollection): string | undefined {
  return (
    rommAssetUrl(apiBase, c.path_cover_large) ??
    rommAssetUrl(apiBase, c.path_cover_small) ??
    firstCoverUrl(apiBase, c.path_covers_large) ??
    firstCoverUrl(apiBase, c.path_covers_small) ??
    rommAssetUrl(apiBase, c.url_cover ?? undefined)
  );
}

function collectionRowKey(c: RommCollection): string {
  if (c.is_virtual) return `v-${c.id}`;
  if (c.is_smart) return `s-${c.id}`;
  return `r-${c.id}`;
}

/** First line under poster: min–max game release years from RomM `/roms` metadata. */
function metaPrimaryLine(
  resolved: string | undefined,
  spansLoading: boolean,
): string {
  if (resolved !== undefined) return resolved;
  if (spansLoading) return "…";
  return "—";
}

async function fetchCollectionArrays(
  session: Session,
  virtualType: VirtualCollectionType,
): Promise<RommCollection[]> {
  const regularP = invoke<string>("romm_api_get", {
    apiBase: session.apiBase,
    accessToken: session.accessToken,
    path: "collections",
    query: null,
  });
  const smartP = invoke<string>("romm_api_get", {
    apiBase: session.apiBase,
    accessToken: session.accessToken,
    path: "collections/smart",
    query: null,
  });
  /** Autogenerated virtual groups — one IGDB bucket (`franchise` or `collection`). */
  const virtualP = invoke<string>("romm_api_get", {
    apiBase: session.apiBase,
    accessToken: session.accessToken,
    path: "collections/virtual",
    query: `type=${virtualType}`,
  });

  const [regOutcome, smartOutcome, virtOutcome] = await Promise.allSettled([
    regularP,
    smartP,
    virtualP,
  ]);

  const taggedRegular: RommCollection[] = [];
  if (regOutcome.status === "fulfilled") {
    try {
      const regular = JSON.parse(regOutcome.value) as RommCollection[];
      if (Array.isArray(regular)) {
        taggedRegular.push(...regular.map((c) => ({ ...c, is_smart: false })));
      }
    } catch {
      /* ignore malformed */
    }
  }

  const taggedSmart: RommCollection[] = [];
  if (smartOutcome.status === "fulfilled") {
    try {
      const smart = JSON.parse(smartOutcome.value) as RommCollection[];
      if (Array.isArray(smart)) {
        taggedSmart.push(...smart.map((c) => ({ ...c, is_smart: true })));
      }
    } catch {
      /* ignore malformed */
    }
  }

  const taggedVirtual: RommCollection[] = [];
  if (virtOutcome.status === "fulfilled") {
    try {
      const virtual = JSON.parse(virtOutcome.value) as Record<
        string,
        unknown
      >[];
      if (Array.isArray(virtual)) {
        for (const row of virtual) {
          const typeField =
            typeof row.type === "string" ? row.type : undefined;
          taggedVirtual.push({
            ...(row as unknown as RommCollection),
            is_smart: false,
            is_virtual: true,
            collection_type: typeField,
          });
        }
      }
    } catch {
      /* ignore malformed */
    }
  }

  const combined = [
    ...taggedRegular,
    ...taggedSmart,
    ...taggedVirtual,
  ].sort((a, b) =>
    a.name.localeCompare(b.name, undefined, { sensitivity: "base" }),
  );

  if (combined.length === 0) {
    if (regOutcome.status === "rejected") throw regOutcome.reason;
    if (virtOutcome.status === "rejected") throw virtOutcome.reason;
    if (smartOutcome.status === "rejected") throw smartOutcome.reason;
  }

  return combined;
}

export function CollectionsView({ session, onLogout }: Props) {
  const [virtualType, setVirtualType] = useState<VirtualCollectionType>(() =>
    loadVirtualCollectionType(),
  );
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [items, setItems] = useState<RommCollection[]>([]);
  const [focusIndex, setFocusIndex] = useState(0);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [releaseLabels, setReleaseLabels] = useState<Record<string, string>>(
    {},
  );
  const [yearSpansLoading, setYearSpansLoading] = useState(false);
  const carouselViewportRef = useRef<HTMLDivElement>(null);
  const carouselTrackRef = useRef<HTMLDivElement>(null);
  const focusSlotRef = useRef<HTMLButtonElement | null>(null);
  const settingsWrapRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      setLoading(true);
      setError(null);
      try {
        const list = await fetchCollectionArrays(session, virtualType);
        if (!cancelled) {
          setItems(list);
          setFocusIndex(0);
        }
      } catch (e) {
        if (!cancelled) setError(formatInvokeError(e));
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [session, virtualType]);

  useEffect(() => {
    if (loading || items.length === 0) {
      setReleaseLabels({});
      setYearSpansLoading(false);
      return;
    }
    let cancelled = false;
    setReleaseLabels({});
    setYearSpansLoading(true);
    void (async () => {
      await mapPool(items, FETCH_CONCURRENCY, async (c) => {
        const key = collectionRowKey(c);
        try {
          const label = await fetchReleaseYearLabel(session, c);
          if (!cancelled) {
            setReleaseLabels((prev) => ({ ...prev, [key]: label }));
          }
        } catch {
          if (!cancelled) {
            setReleaseLabels((prev) => ({ ...prev, [key]: "—" }));
          }
        }
      });
      if (!cancelled) setYearSpansLoading(false);
    })();
    return () => {
      cancelled = true;
      setYearSpansLoading(false);
    };
  }, [session, items, loading]);

  const onRefreshLibrary = useCallback(async () => {
    setRefreshing(true);
    setError(null);
    try {
      const list = await fetchCollectionArrays(session, virtualType);
      setItems(list);
      setFocusIndex((i) =>
        list.length === 0 ? 0 : Math.min(i, list.length - 1),
      );
    } catch (e) {
      setError(formatInvokeError(e));
    } finally {
      setRefreshing(false);
    }
  }, [session, virtualType]);

  useEffect(() => {
    if (!settingsOpen) return;
    function onPointerDown(e: MouseEvent | PointerEvent) {
      const el = settingsWrapRef.current;
      if (el && !el.contains(e.target as Node)) {
        setSettingsOpen(false);
      }
    }
    document.addEventListener("pointerdown", onPointerDown);
    return () => document.removeEventListener("pointerdown", onPointerDown);
  }, [settingsOpen]);

  function selectVirtualType(next: VirtualCollectionType) {
    saveVirtualCollectionType(next);
    setVirtualType(next);
    setSettingsOpen(false);
  }

  /** Keep the focused card’s horizontal center aligned with the viewport center. */
  useLayoutEffect(() => {
    const vp = carouselViewportRef.current;
    const track = carouselTrackRef.current;
    const focusEl = focusSlotRef.current;
    if (!vp || !track || !focusEl || loading || items.length === 0) {
      if (track) track.style.transform = "translateX(0)";
      return;
    }

    const align = () => {
      const vr = vp.getBoundingClientRect();
      const fr = focusEl.getBoundingClientRect();
      const dx = vr.left + vr.width / 2 - (fr.left + fr.width / 2);
      track.style.transform = `translateX(${dx}px)`;
    };

    align();
    const ro = new ResizeObserver(() => requestAnimationFrame(align));
    ro.observe(vp);
    ro.observe(track);
    return () => ro.disconnect();
  }, [focusIndex, items.length, loading, refreshing]);

  const focused = items[focusIndex];
  const bgUrl = useMemo(
    () => (focused ? coverForCollection(session.apiBase, focused) : undefined),
    [focused, session.apiBase],
  );

  const moveFocus = useCallback(
    (delta: number) => {
      if (items.length === 0) return;
      setFocusIndex((i) => {
        const n = items.length;
        return (i + delta + n) % n;
      });
    },
    [items.length],
  );

  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") {
        if (settingsOpen) {
          e.preventDefault();
          setSettingsOpen(false);
          return;
        }
        e.preventDefault();
        onLogout();
        return;
      }
      if (e.key === "ArrowLeft") {
        e.preventDefault();
        moveFocus(-1);
      } else if (e.key === "ArrowRight") {
        e.preventDefault();
        moveFocus(1);
      } else if (e.key === "Backspace") {
        e.preventDefault();
        onLogout();
      }
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [moveFocus, onLogout, settingsOpen]);

  const slots = useMemo(() => [-2, -1, 0, 1, 2], []);

  return (
    <div className="collections-screen">
      <div className="collections-settings-wrap" ref={settingsWrapRef}>
        <button
          type="button"
          className="collections-settings"
          aria-expanded={settingsOpen}
          aria-haspopup="true"
          aria-controls="collections-settings-menu"
          onClick={() => setSettingsOpen((o) => !o)}
          title="Collection settings"
        >
          <span className="collections-settings-icon" aria-hidden>
            ⚙
          </span>
          Settings
        </button>
        {settingsOpen ? (
          <div
            id="collections-settings-menu"
            className="collections-settings-menu"
            role="menu"
            aria-label="Autogenerated collection filter"
          >
            <p className="collections-settings-menu-title">
              Autogenerated groups
            </p>
            <p className="collections-settings-menu-hint">
              Same option as RomM’s virtual collection type (IGDB metadata).
            </p>
            <label className="collections-settings-option">
              <input
                type="radio"
                name="virtual-type"
                checked={virtualType === "collection"}
                onChange={() => selectVirtualType("collection")}
              />
              <span>
                <strong>IGDB collection</strong>
                <span className="collections-settings-option-desc">
                  Series / collection names from IGDB (RomM default).
                </span>
              </span>
            </label>
            <label className="collections-settings-option">
              <input
                type="radio"
                name="virtual-type"
                checked={virtualType === "franchise"}
                onChange={() => selectVirtualType("franchise")}
              />
              <span>
                <strong>Franchise</strong>
                <span className="collections-settings-option-desc">
                  Group by franchise (e.g. Super Mario).
                </span>
              </span>
            </label>
          </div>
        ) : null}
      </div>

      <button
        type="button"
        className="collections-refresh"
        onClick={() => void onRefreshLibrary()}
        disabled={loading || refreshing}
        title="Reload collections from RomM"
      >
        {refreshing ? "Refreshing…" : "Refresh library"}
      </button>

      <div
        className="collections-bg"
        style={
          bgUrl
            ? {
                backgroundImage: `url("${bgUrl.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}")`,
              }
            : undefined
        }
      />
      <div className="collections-bg-scrim" />

      <header className="collections-header">
        <h1 className="collections-title">COLLECTIONS</h1>
        <p className="collections-subtitle">Browse your game collections</p>
      </header>

      {loading ? (
        <p className="collections-status">Loading collections…</p>
      ) : null}
      {error ? (
        <p className="collections-error" role="alert">
          {error}
        </p>
      ) : null}

      {!loading && !error && items.length === 0 ? (
        <p className="collections-status">
          No collections found. Add manual or smart collections in RomM, or
          enable autogenerated groups in library settings—then log in again.
        </p>
      ) : null}

      {!loading && items.length > 0 ? (
        <div
          className="collections-carousel-viewport"
          ref={carouselViewportRef}
        >
          <div
            className="collections-carousel-track"
            ref={carouselTrackRef}
            role="list"
          >
            {slots.map((offset) => {
              const idx = focusIndex + offset;
              const c = items[idx];
              const isFocus = offset === 0;
              const isPlaceholder = idx < 0 || idx >= items.length;

              if (isPlaceholder) {
                return (
                  <div
                    key={`empty-${offset}`}
                    className="collection-slot collection-slot--empty"
                    aria-hidden
                  >
                    <div className="collection-poster collection-poster--empty" />
                    <div className="collection-meta">
                      <span className="collection-years"> </span>
                      <span className="collection-label"> </span>
                    </div>
                  </div>
                );
              }

              const cover = coverForCollection(session.apiBase, c);
              return (
                <button
                  key={`${collectionRowKey(c)}-${idx}`}
                  ref={isFocus ? focusSlotRef : undefined}
                  type="button"
                  role="listitem"
                  className={`collection-slot${isFocus ? " collection-slot--focus" : ""}`}
                  onClick={() => setFocusIndex(idx)}
                >
                <div
                  className={`collection-poster${isFocus ? " collection-poster--focus" : ""}`}
                >
                  {cover ? (
                    <img src={cover} alt="" loading="lazy" />
                  ) : (
                    <span className="collection-poster-fallback">{c.name}</span>
                  )}
                </div>
                <div className="collection-meta">
                  <span className="collection-years">
                    {metaPrimaryLine(
                      releaseLabels[collectionRowKey(c)],
                      yearSpansLoading,
                    )}
                  </span>
                  <span className="collection-label">{c.name}</span>
                </div>
                </button>
              );
            })}
          </div>
        </div>
      ) : null}

      <footer className="collections-footer">
        <div className="footer-hint">
          <span className="footer-keys" aria-hidden>
            <kbd>←</kbd>
            <kbd>→</kbd>
          </span>
          <span>Move</span>
        </div>
        <div className="footer-hint">
          <span className="footer-btn footer-btn--a" aria-hidden>
            A
          </span>
          <span>Select</span>
        </div>
        <div className="footer-hint">
          <span className="footer-btn footer-btn--x" aria-hidden>
            X
          </span>
          <span>Launch</span>
        </div>
      </footer>

      <button type="button" className="collections-logout" onClick={onLogout}>
        <span className="footer-btn footer-btn--b" aria-hidden>
          B
        </span>
        Back to login
      </button>
    </div>
  );
}
